Pullrequest
Cadiducho/40ServidoresMC pull request #41
Opened 2022-06-18 20:35 UTC by apatuka

El tópico principa de este PR es sobre eventos.

He creado un evento llamado Vote40Event que permitirá a los desarrolladores implementar en sus plugins disparadores que se ejecuten al ser llamado el Vote40Event.

Adicional a eso he encontrado algunos inconvenientes realizando pruebas, los cuales ya he corregido, todo podrá visualizarse dentro del PR.

2022-06-21 16:09 UTC, Nestu14 commented
No se si Cadiducho tendrá intención de añadir el evento o no, pero más allá de esos un par de cosas.

Teniendo en cuenta que el propio plugin permite añadir comandos que se ejecuten cuando alguien realiza el voto, ¿qué beneficio tiene añadir el evento que has creado? El único motivo por el que habría beneficio de usar un evento es poder modificar las recompensas o cancelarlas junto al broadcast, algo que no permite lo que has hecho.

A parte de eso, al hacer una PR deberías centrarla en algo especifico y no hacer cambios innecesarios para eso como los arreglos que mencionas o el workflow que has añadido.

2022-06-22 12:27 UTC, Cadiducho requested changes
Hola, antes que nada darte las gracias por querer colaborar.
Como comenta @Nestu14 , puestos a añadir el evento; lo suyo sería que se pudiese cancelar y no diese las recompensas. Me parecería una mejor idea para quien decidiese implementar un plugin sobre este y ocasionalmente modificar su comportamiento. Tener simplemente el evento sin más, para interceptarlo, no me parece tan buena idea: cuando un jugador vota, ya puedes poner que se ejecute cualquier comando y, por lo tanto, implementar tú cualquier funcionalidad sin necesidad de eventos.

En cualquier caso, no sé si te has equivocado haciendo el PullRequest y has añadido más cosas, pero no trae únicamente lo que propones. De hecho, trae cosas que rompen o cambian el correcto funcionamiento del plugin, como te he anotado en la revisión

2022-06-22 12:27 UTC, Cadiducho commented on .github/workflows/maven-publish.yml
> +      run: mvn -B package --file pom.xml
Este archivo rompe el flujo de compilación. No tengo ninguna clave ni una acción configurada para publicar los artifacts a un repositorio Maven de manera automática... de hecho, ni compilo con Maven, lo hago con Gradle. Así que esto sería un error agregarlo al repositorio

2022-06-22 12:27 UTC, Cadiducho commented on bukkit/src/main/java/com/cadiducho/cservidoresmc/bukkit/BukkitPlugin.java
> +        System.out.println("DESPACHO "+command);
esto entiendo que se te ha olvidado quitarlo, pero habría que quitarlo

2022-06-22 12:27 UTC, Cadiducho commented on bukkit/src/main/java/com/cadiducho/cservidoresmc/bukkit/BukkitPlugin.java
> +            Bukkit.getScheduler().callSyncMethod( this, () -> Bukkit.dispatchCommand( getServer().getConsoleSender(), command ) ).get();
Sobre esto, unas cosas:

- ¿Por qué cambiar esto que ejecuta el comando y no tiene nada que ver con el motivo del PR?
- Sobre el uso de `Bukkit`. No entiendo la necesidad de usar una referencia estática en esto, cuando funciona de manera correcta la referencia a `getServer()`, en un ámbito como este método, que no es static. Agregar esto me parece un error pues es agregar un import y cambiar la forma de escribir el código respecto a como ya está escrito en otras partes del plugin, sin la necesidad de usar el singleton de `Bukkit`. No veo bien usar referencias estáticas cuando no es necesario.
- ¿Por qué hacer una referencia a `callSyncMethod` si el método del comando ya se ejecuta en el hilo principal de servidor?. Además, es absurdo mandarlo a otro hilo y a la vez bloquear la ejecución hasta que se ejecute con el `get()`. En todo caso, esto simplemente ejecutaría el comando, pero el Future no devolvería nada, así que esperar a que se devuelva algo y bloquear el hilo principal es absurdo

2022-06-22 12:27 UTC, Cadiducho commented on bukkit/src/main/java/com/cadiducho/cservidoresmc/bukkit/BukkitPlugin.java
> +        Vote40Event event = new Vote40Event((Player)bsender.getSender());
Estaría mejor si el evento pudiese ser cancelable y, en función de si no se ha cancelado, otorgar los premios. Si simplemente se ejecuta un evento me parece un cambio un poco inecesario

2022-06-22 12:27 UTC, Cadiducho commented on bukkit/src/main/java/com/cadiducho/cservidoresmc/bukkit/BukkitPlugin.java
> +            Bukkit.getScheduler().runTask(this, () -> Bukkit.getPluginManager().callEvent(event));
de nuevo, las referencias al singleton de `Bukkit`. Si es posible, deberías usar `getServer()` (y en este caso es posible)

2022-06-22 12:27 UTC, Cadiducho commented on bukkit/src/main/java/com/cadiducho/cservidoresmc/bukkit/CSBukkitConfig.java
> +        reloadCustomCommands();
de nuevo, un cambio que no tiene que ver con la PR

2022-06-22 12:27 UTC, Cadiducho commented on bukkit/src/main/java/com/cadiducho/cservidoresmc/bukkit/CSBukkitConfig.java
> +        comandosCustom = bukkitPlugin.getConfig().getBoolean("broadcast.activado");
Otro cambio que no tiene que ver con los eventos.
Esto rompe el funcionamiento del plugin. En lugar de comprobar si se tiene activado en la config los comandos custom y tener un valor por defecto, tú lo cambias por la configuración del `broadcast`, que son independientes. También, quitas el valor por defecto sin motivo

2022-06-22 12:27 UTC, Cadiducho commented on bukkit/src/main/java/com/cadiducho/cservidoresmc/bukkit/CSBukkitConfig.java
> +            bukkitPlugin.logError("No se ha podido cargar los premios de comandos customizados! (Desactivado)");
este else se ejecutaría cada vez que alguien tiene en su configuración los comandos custom desactivados, pero no es que no se hayan podido cargar ni que haya dado un error, es que quien ha configurado el plugin ha querido que así fuese (de estar la revisión de arriba bien planteada).
No tiene sentido que porque alguien quiera desactivar una funcionalidad del plugin que está en la configuración se le informe como **error** que lo tiene desactivado. No es un error. Lo tiene así porque así lo ha configurado, por eso tampoco tiene sentido informarlo cada vez que lo recargue.

2022-06-22 12:27 UTC, Cadiducho commented on bukkit/src/main/java/com/cadiducho/cservidoresmc/bukkit/Vote40Event.java
> +public class Vote40Event extends Event implements Cancellable {
lo que comenté arriba: Dado que el evento se puede cancelar, lo suyo es que cuando se ejecuta compruebe si se ha cancelado o no, y en ese caso se darían premios o no.
Yo entiendo que eso es mejor idea. 
Si no, implementar Cancellable para no usarlo tampoco tiene mucho sentido

2022-06-22 12:27 UTC, Cadiducho commented on common/src/main/java/com/cadiducho/cservidoresmc/cmd/VoteCMD.java
> +                    .forEach(cmd -> plugin.dispatchCommand(cmd));
¿Por qué cambiar esto? Ni tiene que ver con los eventos, ni es un funcionamiento incorrecto.

En cualquier caso, cambiar una referencia lambda a un método por una que desglosa su argumento, cuando se sobreentiende el argumento, me parece incorrecto

2022-06-22 12:27 UTC, Cadiducho commented on common/src/main/java/com/cadiducho/cservidoresmc/cmd/VoteCMD.java
> +                    plugin.dispatchEvent(sender);
lo dicho, me parece mejor idea comprobar esto arriba antes de dar los premios y mostrar el broadcast

2022-06-22 13:42 UTC, apatuka commented on .github/workflows/maven-publish.yml
> +      run: mvn -B package --file pom.xml
Acabo de eliminar esto, por accidente se incluyó.

2022-06-22 13:43 UTC, apatuka commented on bukkit/src/main/java/com/cadiducho/cservidoresmc/bukkit/BukkitPlugin.java
> +        System.out.println("DESPACHO "+command);
Error mio ! Muchas gracias por notarlo.

2022-06-22 13:45 UTC, apatuka commented on bukkit/src/main/java/com/cadiducho/cservidoresmc/bukkit/BukkitPlugin.java
> +            Bukkit.getScheduler().callSyncMethod( this, () -> Bukkit.dispatchCommand( getServer().getConsoleSender(), command ) ).get();
El motivo por la cual hago callSyncMethod es porque me arrojaba error, lo he revertido como estaba originalmente.

2022-06-22 13:47 UTC, apatuka commented on bukkit/src/main/java/com/cadiducho/cservidoresmc/bukkit/BukkitPlugin.java
> +        Vote40Event event = new Vote40Event((Player)bsender.getSender());
Para esto, hago que el dispatchEvent retorne un valor booleano, entonces en Voto40CMD se verifica el valor booleano que retorne para ejecutar el resto de la función.

2022-06-22 13:48 UTC, apatuka commented on bukkit/src/main/java/com/cadiducho/cservidoresmc/bukkit/BukkitPlugin.java
> +            Bukkit.getScheduler().runTask(this, () -> Bukkit.getPluginManager().callEvent(event));
He cambiado de Bukkit a getServer()

2022-06-22 13:48 UTC, apatuka commented on bukkit/src/main/java/com/cadiducho/cservidoresmc/bukkit/CSBukkitConfig.java
> +        reloadCustomCommands();
Revertido

2022-07-02 04:40 UTC, closed without merging